/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_CARSERVER_VEHICLE_PB_H_INCLUDED
#define PB_CARSERVER_VEHICLE_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _CarServer_ClimateState_CopActivationTemp {
    CarServer_ClimateState_CopActivationTemp_CopActivationTempUnspecified = 0,
    CarServer_ClimateState_CopActivationTemp_CopActivationTempLow = 1,
    CarServer_ClimateState_CopActivationTemp_CopActivationTempMedium = 2,
    CarServer_ClimateState_CopActivationTemp_CopActivationTempHigh = 3
} CarServer_ClimateState_CopActivationTemp;

/* Struct definitions */
typedef struct _CarServer_VehicleState_GuestMode {
    bool GuestModeActive;
} CarServer_VehicleState_GuestMode;

typedef struct _CarServer_VehicleState {
    bool has_guestMode;
    CarServer_VehicleState_GuestMode guestMode;
} CarServer_VehicleState;

typedef struct _CarServer_ClimateState {
    char dummy_field;
} CarServer_ClimateState;

typedef struct _CarServer_ShiftState {
    pb_size_t which_type;
    union {
        CarServer_Void Invalid;
        CarServer_Void P;
        CarServer_Void R;
        CarServer_Void N;
        CarServer_Void D;
        CarServer_Void SNA;
    } type;
} CarServer_ShiftState;

typedef struct _CarServer_DriveState {
    bool has_shift_state;
    CarServer_ShiftState shift_state;
} CarServer_DriveState;

typedef struct _CarServer_VehicleData {
    bool has_drive_state;
    CarServer_DriveState drive_state;
} CarServer_VehicleData;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _CarServer_ClimateState_CopActivationTemp_MIN CarServer_ClimateState_CopActivationTemp_CopActivationTempUnspecified
#define _CarServer_ClimateState_CopActivationTemp_MAX CarServer_ClimateState_CopActivationTemp_CopActivationTempHigh
#define _CarServer_ClimateState_CopActivationTemp_ARRAYSIZE ((CarServer_ClimateState_CopActivationTemp)(CarServer_ClimateState_CopActivationTemp_CopActivationTempHigh+1))








/* Initializer values for message structs */
#define CarServer_VehicleState_init_default      {false, CarServer_VehicleState_GuestMode_init_default}
#define CarServer_VehicleState_GuestMode_init_default {0}
#define CarServer_ClimateState_init_default      {0}
#define CarServer_VehicleData_init_default       {false, CarServer_DriveState_init_default}
#define CarServer_DriveState_init_default        {false, CarServer_ShiftState_init_default}
#define CarServer_ShiftState_init_default        {0, {CarServer_Void_init_default}}
#define CarServer_VehicleState_init_zero         {false, CarServer_VehicleState_GuestMode_init_zero}
#define CarServer_VehicleState_GuestMode_init_zero {0}
#define CarServer_ClimateState_init_zero         {0}
#define CarServer_VehicleData_init_zero          {false, CarServer_DriveState_init_zero}
#define CarServer_DriveState_init_zero           {false, CarServer_ShiftState_init_zero}
#define CarServer_ShiftState_init_zero           {0, {CarServer_Void_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define CarServer_VehicleState_GuestMode_GuestModeActive_tag 1
#define CarServer_VehicleState_guestMode_tag     74
#define CarServer_ShiftState_Invalid_tag         1
#define CarServer_ShiftState_P_tag               2
#define CarServer_ShiftState_R_tag               3
#define CarServer_ShiftState_N_tag               4
#define CarServer_ShiftState_D_tag               5
#define CarServer_ShiftState_SNA_tag             6
#define CarServer_DriveState_shift_state_tag     1
#define CarServer_VehicleData_drive_state_tag    5

/* Struct field encoding specification for nanopb */
#define CarServer_VehicleState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  guestMode,        74)
#define CarServer_VehicleState_CALLBACK NULL
#define CarServer_VehicleState_DEFAULT NULL
#define CarServer_VehicleState_guestMode_MSGTYPE CarServer_VehicleState_GuestMode

#define CarServer_VehicleState_GuestMode_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     GuestModeActive,   1)
#define CarServer_VehicleState_GuestMode_CALLBACK NULL
#define CarServer_VehicleState_GuestMode_DEFAULT NULL

#define CarServer_ClimateState_FIELDLIST(X, a) \

#define CarServer_ClimateState_CALLBACK NULL
#define CarServer_ClimateState_DEFAULT NULL

#define CarServer_VehicleData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  drive_state,       5)
#define CarServer_VehicleData_CALLBACK NULL
#define CarServer_VehicleData_DEFAULT NULL
#define CarServer_VehicleData_drive_state_MSGTYPE CarServer_DriveState

#define CarServer_DriveState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  shift_state,       1)
#define CarServer_DriveState_CALLBACK NULL
#define CarServer_DriveState_DEFAULT NULL
#define CarServer_DriveState_shift_state_MSGTYPE CarServer_ShiftState

#define CarServer_ShiftState_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,Invalid,type.Invalid),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,P,type.P),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,R,type.R),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,N,type.N),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,D,type.D),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,SNA,type.SNA),   6)
#define CarServer_ShiftState_CALLBACK NULL
#define CarServer_ShiftState_DEFAULT NULL
#define CarServer_ShiftState_type_Invalid_MSGTYPE CarServer_Void
#define CarServer_ShiftState_type_P_MSGTYPE CarServer_Void
#define CarServer_ShiftState_type_R_MSGTYPE CarServer_Void
#define CarServer_ShiftState_type_N_MSGTYPE CarServer_Void
#define CarServer_ShiftState_type_D_MSGTYPE CarServer_Void
#define CarServer_ShiftState_type_SNA_MSGTYPE CarServer_Void

extern const pb_msgdesc_t CarServer_VehicleState_msg;
extern const pb_msgdesc_t CarServer_VehicleState_GuestMode_msg;
extern const pb_msgdesc_t CarServer_ClimateState_msg;
extern const pb_msgdesc_t CarServer_VehicleData_msg;
extern const pb_msgdesc_t CarServer_DriveState_msg;
extern const pb_msgdesc_t CarServer_ShiftState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CarServer_VehicleState_fields &CarServer_VehicleState_msg
#define CarServer_VehicleState_GuestMode_fields &CarServer_VehicleState_GuestMode_msg
#define CarServer_ClimateState_fields &CarServer_ClimateState_msg
#define CarServer_VehicleData_fields &CarServer_VehicleData_msg
#define CarServer_DriveState_fields &CarServer_DriveState_msg
#define CarServer_ShiftState_fields &CarServer_ShiftState_msg

/* Maximum encoded size of messages (where known) */
#define CARSERVER_VEHICLE_PB_H_MAX_SIZE          CarServer_VehicleData_size
#define CarServer_ClimateState_size              0
#define CarServer_DriveState_size                4
#define CarServer_ShiftState_size                2
#define CarServer_VehicleData_size               6
#define CarServer_VehicleState_GuestMode_size    2
#define CarServer_VehicleState_size              5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
